root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd"
bin = "./tmp/main"
full_bin = "./tmp/main"

include_ext = ["go"]
include_dir = ["cmd", "internal"]

exclude_dir = [
    "tmp",
    "vendor",
    ".git",
]

exclude_file = []
exclude_regex = ["_test.go"]

delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[log]
time = true

[color]
main = "cyan"
watcher = "yellow"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true